package com.moai.animelist.vista;

//import block
import com.moai.animelist.controlador.*;
import com.moai.animelist.modelo.*;
import java.io.*;

/**
 *
 * @author moai-san (Leonardo Gonzalez)
 * @author nlago (Nicolás Lagos)
 * @author maca (Macarena Troncoso)
 */

public class Menu_Window extends javax.swing.JFrame
{
    private static CollectionManagement llamar = new CollectionManagement();
    private static ReportUsers userMan= new ReportUsers();
    private static ReportAnime aniMan;
    private final String username;
    private ListarFiltrados_Ventana ventanaFiltrados;
    private AddAnime_Window ventanaAdd_Anime;
    private ListarAnos_Ventana ventanaMostrarAnos;
    private UserLists_Window accionesDe_usuario;
    private AddYear_Window dialogoAgregar_ano;
    private Ventana_FiltradoDoble filtradoDoble_dialog;
    private Ventana_EliminarAnime dialogoEliminar_anime;
    private Ventana_EliminarAno dialogoEliminar_ano;
    private Ventana_ModificarAnime dialogoModificar_anime;
    private Ventana_ModificarAno dialogoModificar_ano;
    
    /**
     *
     * @param user Administrador
     * @throws IOException Error de I/O
     * @throws FileNotFoundException Error de archivo no encontrado
     */
    public Menu_Window(UsuarioAdministrador user)throws IOException, FileNotFoundException
    {
        llamar.importCatalogue();
        llamar.importUser_data(user.getUsername());
        initComponents();
        setLocationRelativeTo(null);
        errorDialog.setLocationRelativeTo(null);
        okDialog.setLocationRelativeTo(null);
        username = user.getUsername();
        //si bien no es necesario, se llama al Garbage collector para limpiar la memoria usada por el login y la apertura de archivos al llenar las colecciones.
        System.gc();
    }
    
    /**
     *
     * @param user Usuario comun
     * @throws IOException Error de I/O
     * @throws FileNotFoundException Error de archivo no encontrado
     */
    public Menu_Window(UsuarioComun user)throws IOException, FileNotFoundException
    {
        llamar.importCatalogue();
        llamar.importUser_data(user.getUsername());
        initComponents();
        setLocationRelativeTo(null);
        errorDialog.setLocationRelativeTo(null);
        okDialog.setLocationRelativeTo(null);
        username = user.getUsername();
        
        //Invisibilisamos los botones
        botonAgregar_anime.setVisible(false);
        botonAgregar_ano.setVisible(false);
        botonEliminar_anime1.setVisible(false);
        botonEliminar_ano.setVisible(false);
        botonModificar_anime1.setVisible(false);
        botonModificar_ano.setVisible(false);
        botonCrear_CSV.setVisible(false);
        botonCrear_Excel.setVisible(false);
        usersCSV_button.setVisible(false);
        usersExcel_button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        errorDialog = new javax.swing.JDialog();
        volverA_menuFrom_error = new javax.swing.JButton();
        tituloError = new javax.swing.JLabel();
        okDialog = new javax.swing.JDialog();
        tituloOk = new javax.swing.JLabel();
        returnTo_menu5 = new javax.swing.JButton();
        botonAgregar_anime = new javax.swing.JButton();
        botonAgregar_ano = new javax.swing.JButton();
        botonMostrar_ano = new javax.swing.JButton();
        botonBuscar_porAno = new javax.swing.JButton();
        botonBuscar_porTipo = new javax.swing.JButton();
        botonBuscar_porGenero = new javax.swing.JButton();
        botonEliminar_anime1 = new javax.swing.JButton();
        botonEliminar_ano = new javax.swing.JButton();
        botonModificar_anime1 = new javax.swing.JButton();
        botonModificar_ano = new javax.swing.JButton();
        botonCrear_CSV = new javax.swing.JButton();
        botonCrear_Excel = new javax.swing.JButton();
        closeBoton = new javax.swing.JButton();
        addTo_listButton = new javax.swing.JButton();
        botonFiltrado_2Generos = new javax.swing.JButton();
        usersExcel_button = new javax.swing.JButton();
        usersCSV_button = new javax.swing.JButton();

        errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setResizable(false);
        errorDialog.setSize(new java.awt.Dimension(400, 210));

        volverA_menuFrom_error.setText("Volver al Menu");
        volverA_menuFrom_error.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                volverA_menuFrom_errorActionPerformed(evt);
            }
        });

        tituloError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloError.setText("ERROR!!");

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(volverA_menuFrom_error, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(tituloError)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tituloError)
                .addGap(76, 76, 76)
                .addComponent(volverA_menuFrom_error)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        okDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        okDialog.setAlwaysOnTop(true);
        okDialog.setResizable(false);
        okDialog.setSize(new java.awt.Dimension(400, 210));

        tituloOk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloOk.setText("ACCION COMPLETADA!!");

        returnTo_menu5.setText("Volver al Menu");
        returnTo_menu5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnTo_menu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okDialogLayout = new javax.swing.GroupLayout(okDialog.getContentPane());
        okDialog.getContentPane().setLayout(okDialogLayout);
        okDialogLayout.setHorizontalGroup(
            okDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okDialogLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(returnTo_menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okDialogLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(tituloOk, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        okDialogLayout.setVerticalGroup(
            okDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloOk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(returnTo_menu5)
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moai AnimeList");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(430, 800));

        botonAgregar_anime.setText("Agregar Anime");
        botonAgregar_anime.setMaximumSize(new java.awt.Dimension(200, 22));
        botonAgregar_anime.setMinimumSize(new java.awt.Dimension(200, 22));
        botonAgregar_anime.setPreferredSize(new java.awt.Dimension(200, 22));
        botonAgregar_anime.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAgregar_animeActionPerformed(evt);
            }
        });

        botonAgregar_ano.setText("Agregar Año de Publicacion");
        botonAgregar_ano.setMaximumSize(new java.awt.Dimension(200, 22));
        botonAgregar_ano.setMinimumSize(new java.awt.Dimension(200, 22));
        botonAgregar_ano.setPreferredSize(new java.awt.Dimension(200, 22));
        botonAgregar_ano.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAgregar_anoActionPerformed(evt);
            }
        });

        botonMostrar_ano.setText("Mostrar Años");
        botonMostrar_ano.setMaximumSize(new java.awt.Dimension(200, 22));
        botonMostrar_ano.setMinimumSize(new java.awt.Dimension(200, 22));
        botonMostrar_ano.setPreferredSize(new java.awt.Dimension(200, 22));
        botonMostrar_ano.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonMostrar_anoActionPerformed(evt);
            }
        });

        botonBuscar_porAno.setText("Mostrar Animes de \"x\" año");
        botonBuscar_porAno.setMaximumSize(new java.awt.Dimension(200, 22));
        botonBuscar_porAno.setMinimumSize(new java.awt.Dimension(200, 22));
        botonBuscar_porAno.setPreferredSize(new java.awt.Dimension(200, 22));
        botonBuscar_porAno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonBuscar_porAnoActionPerformed(evt);
            }
        });

        botonBuscar_porTipo.setText("Mostrar Animes de \"x\" tipo");
        botonBuscar_porTipo.setMaximumSize(new java.awt.Dimension(200, 22));
        botonBuscar_porTipo.setMinimumSize(new java.awt.Dimension(200, 22));
        botonBuscar_porTipo.setPreferredSize(new java.awt.Dimension(200, 22));
        botonBuscar_porTipo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonBuscar_porTipoActionPerformed(evt);
            }
        });

        botonBuscar_porGenero.setText("Mostrar Animes de \"x\" genero");
        botonBuscar_porGenero.setMaximumSize(new java.awt.Dimension(200, 22));
        botonBuscar_porGenero.setMinimumSize(new java.awt.Dimension(200, 22));
        botonBuscar_porGenero.setPreferredSize(new java.awt.Dimension(200, 22));
        botonBuscar_porGenero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonBuscar_porGeneroActionPerformed(evt);
            }
        });

        botonEliminar_anime1.setText("Eliminar anime");
        botonEliminar_anime1.setMaximumSize(new java.awt.Dimension(200, 22));
        botonEliminar_anime1.setMinimumSize(new java.awt.Dimension(200, 22));
        botonEliminar_anime1.setPreferredSize(new java.awt.Dimension(200, 22));
        botonEliminar_anime1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonEliminar_anime1ActionPerformed(evt);
            }
        });

        botonEliminar_ano.setText("Eliminar Año");
        botonEliminar_ano.setMaximumSize(new java.awt.Dimension(200, 22));
        botonEliminar_ano.setMinimumSize(new java.awt.Dimension(200, 22));
        botonEliminar_ano.setPreferredSize(new java.awt.Dimension(200, 22));
        botonEliminar_ano.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonEliminar_anoActionPerformed(evt);
            }
        });

        botonModificar_anime1.setText("Modificar anime");
        botonModificar_anime1.setMaximumSize(new java.awt.Dimension(200, 22));
        botonModificar_anime1.setMinimumSize(new java.awt.Dimension(200, 22));
        botonModificar_anime1.setPreferredSize(new java.awt.Dimension(200, 22));
        botonModificar_anime1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonModificar_anime1ActionPerformed(evt);
            }
        });

        botonModificar_ano.setText("Modificar Año");
        botonModificar_ano.setMaximumSize(new java.awt.Dimension(200, 22));
        botonModificar_ano.setMinimumSize(new java.awt.Dimension(200, 22));
        botonModificar_ano.setPreferredSize(new java.awt.Dimension(200, 22));
        botonModificar_ano.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonModificar_anoActionPerformed(evt);
            }
        });

        botonCrear_CSV.setText("Exportar Catalogo a Archivo CSV");
        botonCrear_CSV.setMaximumSize(new java.awt.Dimension(200, 22));
        botonCrear_CSV.setMinimumSize(new java.awt.Dimension(200, 22));
        botonCrear_CSV.setPreferredSize(new java.awt.Dimension(200, 22));
        botonCrear_CSV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonCrear_CSVActionPerformed(evt);
            }
        });

        botonCrear_Excel.setText("Exportar Catalogo a Archivo Excel");
        botonCrear_Excel.setMaximumSize(new java.awt.Dimension(200, 22));
        botonCrear_Excel.setMinimumSize(new java.awt.Dimension(200, 22));
        botonCrear_Excel.setPreferredSize(new java.awt.Dimension(200, 22));
        botonCrear_Excel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonCrear_ExcelActionPerformed(evt);
            }
        });

        closeBoton.setText("Cerrar Aplicacion :c");
        closeBoton.setMaximumSize(new java.awt.Dimension(200, 22));
        closeBoton.setMinimumSize(new java.awt.Dimension(200, 22));
        closeBoton.setPreferredSize(new java.awt.Dimension(200, 22));
        closeBoton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeBotonActionPerformed(evt);
            }
        });

        addTo_listButton.setText("Añadir anime a una de mis listas");
        addTo_listButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addTo_listButtonActionPerformed(evt);
            }
        });

        botonFiltrado_2Generos.setText("Filtrar Animes de 2 generos");
        botonFiltrado_2Generos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonFiltrado_2GenerosActionPerformed(evt);
            }
        });

        usersExcel_button.setText("Exportar Listado Usuarios a Archivo Excel");
        usersExcel_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                usersExcel_buttonActionPerformed(evt);
            }
        });

        usersCSV_button.setText("Exportar Listado Usuarios a Archivo CSV");
        usersCSV_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                usersCSV_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usersExcel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usersCSV_button, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addTo_listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonFiltrado_2Generos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonBuscar_porGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminar_anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonModificar_anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonModificar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonCrear_CSV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonCrear_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(closeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonBuscar_porTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonBuscar_porAno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonMostrar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAgregar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAgregar_anime, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botonMostrar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBuscar_porAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBuscar_porTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBuscar_porGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonFiltrado_2Generos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addTo_listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAgregar_anime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAgregar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar_anime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificar_anime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCrear_CSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCrear_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usersCSV_button)
                .addGap(18, 18, 18)
                .addComponent(usersExcel_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(closeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregar_animeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAgregar_animeActionPerformed
    {//GEN-HEADEREND:event_botonAgregar_animeActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            ventanaAdd_Anime =new AddAnime_Window(this,llamar);
            ventanaAdd_Anime.setVisible(true);
    }//GEN-LAST:event_botonAgregar_animeActionPerformed

    private void closeBotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeBotonActionPerformed
    {//GEN-HEADEREND:event_closeBotonActionPerformed
        // TODO add your handling code here:
        try
        {
            ExportData export =new ExportData(llamar.getWatched(),llamar.getFaved(),llamar.getHated());
            export.export_userData(username);
        }
        catch (IOException e){}
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeBotonActionPerformed
    
    private void botonAgregar_anoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAgregar_anoActionPerformed
    {//GEN-HEADEREND:event_botonAgregar_anoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dialogoAgregar_ano =new AddYear_Window(this, llamar);
        dialogoAgregar_ano.setVisible(true);
    }//GEN-LAST:event_botonAgregar_anoActionPerformed

    private void botonBuscar_porAnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscar_porAnoActionPerformed
    {//GEN-HEADEREND:event_botonBuscar_porAnoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventanaFiltrados = new ListarFiltrados_Ventana(0,this,llamar);
        ventanaFiltrados.setVisible(true);
    }//GEN-LAST:event_botonBuscar_porAnoActionPerformed

    private void volverA_menuFrom_errorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volverA_menuFrom_errorActionPerformed
    {//GEN-HEADEREND:event_volverA_menuFrom_errorActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_volverA_menuFrom_errorActionPerformed

    private void botonMostrar_anoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonMostrar_anoActionPerformed
    {//GEN-HEADEREND:event_botonMostrar_anoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventanaMostrarAnos = new ListarAnos_Ventana(this, llamar);
        ventanaMostrarAnos.setVisible(true);
    }//GEN-LAST:event_botonMostrar_anoActionPerformed

    private void botonEliminar_anime1ActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonEliminar_anime1ActionPerformed
        this.setVisible(false);
        dialogoEliminar_anime =new Ventana_EliminarAnime(this,llamar);
        dialogoEliminar_anime.setVisible(true);
    }//GEN-LAST:event_botonEliminar_anime1ActionPerformed

    private void botonModificar_anime1ActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonModificar_anime1ActionPerformed
        this.setVisible(false);
        dialogoModificar_anime =new Ventana_ModificarAnime(this,llamar);
        dialogoModificar_anime.setVisible(true);
    }//GEN-LAST:event_botonModificar_anime1ActionPerformed

    private void botonCrear_CSVActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonCrear_CSVActionPerformed
        // TODO add your handling code here:
        try
        {
            this.setVisible(false);
            aniMan = new ReportAnime(llamar.getCatalogue());
            aniMan.crearArchivoCSV();
            okDialog.setVisible(true);
        }
        catch(IOException e)
        {
            okDialog.dispose();
            errorDialog.setVisible(true);
        }
    }//GEN-LAST:event_botonCrear_CSVActionPerformed

    private void botonCrear_ExcelActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonCrear_ExcelActionPerformed
        // TODO add your handling code here:
        try
        {
            this.setVisible(false);
            aniMan = new ReportAnime(llamar.getCatalogue());
            aniMan.crearArchivoExcel();
            okDialog.setVisible(true);
        }
        catch(IOException e)
        {
            okDialog.dispose();
            errorDialog.setVisible(true);
        }
    }//GEN-LAST:event_botonCrear_ExcelActionPerformed

    private void returnTo_menu5ActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_returnTo_menu5ActionPerformed
        // TODO add your handling code here:
        okDialog.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_returnTo_menu5ActionPerformed

    private void botonEliminar_anoActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonEliminar_anoActionPerformed
        this.setVisible(false);
        dialogoEliminar_ano = new Ventana_EliminarAno(this,llamar);
        dialogoEliminar_ano.setVisible(true);
    }//GEN-LAST:event_botonEliminar_anoActionPerformed

    private void botonModificar_anoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificar_anoActionPerformed
    {//GEN-HEADEREND:event_botonModificar_anoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dialogoModificar_ano =new Ventana_ModificarAno(this,llamar);
        dialogoModificar_ano.setVisible(true);
    }//GEN-LAST:event_botonModificar_anoActionPerformed

    private void botonBuscar_porTipoActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonBuscar_porTipoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventanaFiltrados = new ListarFiltrados_Ventana(1,this,llamar);
        ventanaFiltrados.setVisible(true);
    }//GEN-LAST:event_botonBuscar_porTipoActionPerformed

    private void botonBuscar_porGeneroActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_botonBuscar_porGeneroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventanaFiltrados = new ListarFiltrados_Ventana(2,this,llamar);
        ventanaFiltrados.setVisible(true);
    }//GEN-LAST:event_botonBuscar_porGeneroActionPerformed

    private void addTo_listButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addTo_listButtonActionPerformed
    {//GEN-HEADEREND:event_addTo_listButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        accionesDe_usuario =new UserLists_Window(this,llamar);
        accionesDe_usuario.setVisible(true);
    }//GEN-LAST:event_addTo_listButtonActionPerformed

    private void botonFiltrado_2GenerosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonFiltrado_2GenerosActionPerformed
    {//GEN-HEADEREND:event_botonFiltrado_2GenerosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        filtradoDoble_dialog = new Ventana_FiltradoDoble(this,llamar);
        filtradoDoble_dialog.setVisible(true);
    }//GEN-LAST:event_botonFiltrado_2GenerosActionPerformed

    private void usersCSV_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_usersCSV_buttonActionPerformed
    {//GEN-HEADEREND:event_usersCSV_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try
        {
            userMan.crearArchivoCSV();
            okDialog.setVisible(true);
            return;
        }
        catch(IOException e)
        {
            errorDialog.setVisible(true);
            return;
        }
    }//GEN-LAST:event_usersCSV_buttonActionPerformed

    private void usersExcel_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_usersExcel_buttonActionPerformed
    {//GEN-HEADEREND:event_usersExcel_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try
        {
            userMan.crearArchivoExcel();
            okDialog.setVisible(true);
            return;
        }
        catch(IOException e)
        {
            errorDialog.setVisible(true);
            return;
        }
    }//GEN-LAST:event_usersExcel_buttonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTo_listButton;
    private javax.swing.JButton botonAgregar_anime;
    private javax.swing.JButton botonAgregar_ano;
    private javax.swing.JButton botonBuscar_porAno;
    private javax.swing.JButton botonBuscar_porGenero;
    private javax.swing.JButton botonBuscar_porTipo;
    private javax.swing.JButton botonCrear_CSV;
    private javax.swing.JButton botonCrear_Excel;
    private javax.swing.JButton botonEliminar_anime1;
    private javax.swing.JButton botonEliminar_ano;
    private javax.swing.JButton botonFiltrado_2Generos;
    private javax.swing.JButton botonModificar_anime1;
    private javax.swing.JButton botonModificar_ano;
    private javax.swing.JButton botonMostrar_ano;
    private javax.swing.JButton closeBoton;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JDialog okDialog;
    private javax.swing.JButton returnTo_menu5;
    private javax.swing.JLabel tituloError;
    private javax.swing.JLabel tituloOk;
    private javax.swing.JButton usersCSV_button;
    private javax.swing.JButton usersExcel_button;
    private javax.swing.JButton volverA_menuFrom_error;
    // End of variables declaration//GEN-END:variables
}
