/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moai.animelist.vista;

import com.moai.animelist.controlador.CollectionManagement;
import javax.swing.JFrame;

/**
 *
 * @author moai
 */
public class Ventana_ModificarAnime extends javax.swing.JFrame implements Interface_LimpiezaVentanas
{
    private final JFrame father;
    private final CollectionManagement llamar;
    /**
     * Creates new form Ventana_ModificarAnime
     */
    public Ventana_ModificarAnime(JFrame padre, CollectionManagement toUse)
    {
        initComponents();
        llamar =toUse;
        father =padre;
        this.setLocationRelativeTo(null);
        errorDialog.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        errorDialog = new javax.swing.JDialog();
        volverA_menuFrom_error = new javax.swing.JButton();
        tituloError = new javax.swing.JLabel();
        returnTo_menu_4 = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        textfieldNuevo_id1 = new javax.swing.JTextField();
        textfieldModificar_Anime1 = new javax.swing.JTextField();
        idAnimeText2 = new javax.swing.JLabel();
        nuevoIDText3 = new javax.swing.JLabel();
        tituloModificar_anime1 = new javax.swing.JLabel();

        errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setResizable(false);
        errorDialog.setSize(new java.awt.Dimension(400, 210));

        volverA_menuFrom_error.setText("Volver al Menu");
        volverA_menuFrom_error.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                volverA_menuFrom_errorActionPerformed(evt);
            }
        });

        tituloError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloError.setText("ERROR!!");

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(volverA_menuFrom_error, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(tituloError)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tituloError)
                .addGap(76, 76, 76)
                .addComponent(volverA_menuFrom_error)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(446, 270));
        setResizable(false);
        setSize(new java.awt.Dimension(446, 270));

        returnTo_menu_4.setText("Volver al Menu");
        returnTo_menu_4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnTo_menu_4ActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificarActionPerformed(evt);
            }
        });

        textfieldNuevo_id1.setOpaque(false);

        textfieldModificar_Anime1.setOpaque(false);

        idAnimeText2.setText("ID Anime");

        nuevoIDText3.setText("Nuevo ID");

        tituloModificar_anime1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloModificar_anime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloModificar_anime1.setText("Ingrese ID del Anime A Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloModificar_anime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoIDText3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textfieldNuevo_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idAnimeText2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfieldModificar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(returnTo_menu_4)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloModificar_anime1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAnimeText2)
                    .addComponent(textfieldModificar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoIDText3)
                    .addComponent(textfieldNuevo_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(returnTo_menu_4))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void clearFields()
    {
        textfieldModificar_Anime1.setText("");
        textfieldNuevo_id1.setText("");
    }
    
    private void returnTo_menu_4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnTo_menu_4ActionPerformed
    {//GEN-HEADEREND:event_returnTo_menu_4ActionPerformed
        this.setVisible(false);
        clearFields();
        father.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnTo_menu_4ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificarActionPerformed
    {//GEN-HEADEREND:event_ModificarActionPerformed
        this.setVisible(false);
        String animeID = textfieldModificar_Anime1.getText();
        String nuevoID = textfieldNuevo_id1.getText();
        int modificarID = llamar.modificarID(animeID, nuevoID);
        if(modificarID != 0)
        {
            errorDialog.setVisible(true);
            return;
        }
        father.setVisible(true);
        clearFields();
        this.dispose();
    }//GEN-LAST:event_ModificarActionPerformed

    private void volverA_menuFrom_errorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volverA_menuFrom_errorActionPerformed
    {//GEN-HEADEREND:event_volverA_menuFrom_errorActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
        father.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverA_menuFrom_errorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel idAnimeText2;
    private javax.swing.JLabel nuevoIDText3;
    private javax.swing.JButton returnTo_menu_4;
    private javax.swing.JTextField textfieldModificar_Anime1;
    private javax.swing.JTextField textfieldNuevo_id1;
    private javax.swing.JLabel tituloError;
    private javax.swing.JLabel tituloModificar_anime1;
    private javax.swing.JButton volverA_menuFrom_error;
    // End of variables declaration//GEN-END:variables
}
