package com.moai.animelist.vista;

import com.moai.animelist.controlador.CollectionManagement;
import javax.swing.JFrame;

/**
 * @author moai-san (Leonardo Gonzalez)
 * @author nlago (Nicolás Lagos)
 * @author maca (Macarena Troncoso)
 */

public class Ventana_EliminarAnime extends javax.swing.JFrame implements Interface_LimpiezaVentanas
{
    private final JFrame father;
    private final CollectionManagement llamar;
    
    /**
     * Creates new form Ventana_EliminarAnime
     * 
     * @param padre Menu principal
     * @param toUse Variable de clase CollectionManagement
     */
    public Ventana_EliminarAnime(JFrame padre, CollectionManagement toUse)
    {
        initComponents();
        llamar =toUse;
        father =padre;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        errorDialog = new javax.swing.JDialog();
        volverA_menuFrom_error = new javax.swing.JButton();
        tituloError = new javax.swing.JLabel();
        returnTo_menu_3 = new javax.swing.JButton();
        eliminarAnime = new javax.swing.JButton();
        idAnimeText1 = new javax.swing.JLabel();
        textfieldEliminar_Anime1 = new javax.swing.JTextField();
        tituloEliminar_anime1 = new javax.swing.JLabel();

        errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setResizable(false);
        errorDialog.setSize(new java.awt.Dimension(400, 210));

        volverA_menuFrom_error.setText("Volver al Menu");
        volverA_menuFrom_error.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                volverA_menuFrom_errorActionPerformed(evt);
            }
        });

        tituloError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloError.setText("ERROR!!");

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(volverA_menuFrom_error, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(tituloError)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tituloError)
                .addGap(76, 76, 76)
                .addComponent(volverA_menuFrom_error)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(446, 267));
        setSize(new java.awt.Dimension(446, 267));

        returnTo_menu_3.setText("Volver al Menu");
        returnTo_menu_3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnTo_menu_3ActionPerformed(evt);
            }
        });

        eliminarAnime.setText("Eliminar");
        eliminarAnime.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarAnimeActionPerformed(evt);
            }
        });

        idAnimeText1.setText("ID Anime");

        textfieldEliminar_Anime1.setOpaque(false);
        textfieldEliminar_Anime1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textfieldEliminar_Anime1ActionPerformed(evt);
            }
        });

        tituloEliminar_anime1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloEliminar_anime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloEliminar_anime1.setText("Ingrese ID del Anime A Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(idAnimeText1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfieldEliminar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminarAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnTo_menu_3)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(tituloEliminar_anime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloEliminar_anime1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAnimeText1)
                    .addComponent(textfieldEliminar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarAnime)
                    .addComponent(returnTo_menu_3))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void clearFields()
    {
        textfieldEliminar_Anime1.setText("");
    }
    
    private void returnTo_menu_3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnTo_menu_3ActionPerformed
    {//GEN-HEADEREND:event_returnTo_menu_3ActionPerformed
        this.setVisible(false);
        clearFields();
        father.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnTo_menu_3ActionPerformed

    private void eliminarAnimeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarAnimeActionPerformed
    {//GEN-HEADEREND:event_eliminarAnimeActionPerformed
        String animeID = this.textfieldEliminar_Anime1.getText();
        int eliminarID = llamar.eliminarAnime(animeID);
        this.setVisible(false);
        if(eliminarID != 0)
        {
            errorDialog.setVisible(true);
            return;
        }
        father.setVisible(true);
        clearFields();
        this.dispose();
    }//GEN-LAST:event_eliminarAnimeActionPerformed

    private void textfieldEliminar_Anime1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textfieldEliminar_Anime1ActionPerformed
    {//GEN-HEADEREND:event_textfieldEliminar_Anime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldEliminar_Anime1ActionPerformed

    private void volverA_menuFrom_errorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volverA_menuFrom_errorActionPerformed
    {//GEN-HEADEREND:event_volverA_menuFrom_errorActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
        father.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverA_menuFrom_errorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarAnime;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel idAnimeText1;
    private javax.swing.JButton returnTo_menu_3;
    private javax.swing.JTextField textfieldEliminar_Anime1;
    private javax.swing.JLabel tituloEliminar_anime1;
    private javax.swing.JLabel tituloError;
    private javax.swing.JButton volverA_menuFrom_error;
    // End of variables declaration//GEN-END:variables
}
