package com.moai.animelist;
/**
 * 
 * @author moai-san (Leonardo Gonzalez)
 * 
 */

//import block

import java.io.*;
import com.moai.animelist.*;

public class Menu extends javax.swing.JFrame
{
    static Funciones llamar = new Funciones();
    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
        setLocationRelativeTo(null);
        dialogoAdd_anime.setLocationRelativeTo(null);
        dialogoAgregar_ano.setLocationRelativeTo(null);
        dialogoMostrar_anos.setLocationRelativeTo(null);
        dialogoBuscar_porAnos.setLocationRelativeTo(null);
        outputFiltro_porAno.setLocationRelativeTo(null);
        errorDialog.setLocationRelativeTo(null);
        dialogoEliminar_anime.setLocationRelativeTo(null);
        dialogoModificar_anime.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAdd_anime = new javax.swing.JDialog();
        id_input = new javax.swing.JTextField();
        name_input = new javax.swing.JTextField();
        type_input = new javax.swing.JTextField();
        episodes_input = new javax.swing.JTextField();
        duration_input = new javax.swing.JTextField();
        rating_input = new javax.swing.JTextField();
        year_input = new javax.swing.JTextField();
        studio_input = new javax.swing.JTextField();
        genre_input = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        returnTo_menu = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        iD_display = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        typeDisplay = new javax.swing.JLabel();
        chaptersDisplay = new javax.swing.JLabel();
        durationDisplay = new javax.swing.JLabel();
        ratingDisplay = new javax.swing.JLabel();
        yearDisplay = new javax.swing.JLabel();
        studioDisplay = new javax.swing.JLabel();
        genreDisplay = new javax.swing.JLabel();
        dialogoAgregar_ano = new javax.swing.JDialog();
        tituloAdd_ano = new javax.swing.JLabel();
        anoText = new javax.swing.JLabel();
        toAdd_ano = new javax.swing.JTextField();
        addAno = new javax.swing.JButton();
        returnTo_menu_2 = new javax.swing.JButton();
        dialogoMostrar_anos = new javax.swing.JDialog();
        title2 = new javax.swing.JTextField();
        returnTo_menu_1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDe_anos = new javax.swing.JTable();
        dialogoBuscar_porAnos = new javax.swing.JDialog();
        ano4 = new javax.swing.JTextField();
        inputAno = new javax.swing.JTextField();
        botonBusca_ano = new javax.swing.JButton();
        tituloJDialog4 = new javax.swing.JTextField();
        outputFiltro_porAno = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFiltrados_porAno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        errorDialog = new javax.swing.JDialog();
        volverA_menuFrom_error = new javax.swing.JButton();
        tituloError = new javax.swing.JLabel();
        okDialog = new javax.swing.JDialog();
        dialogoEliminar_anime = new javax.swing.JDialog();
        tituloEliminar_anime1 = new javax.swing.JLabel();
        idAnimeText1 = new javax.swing.JLabel();
        textfieldEliminar_Anime1 = new javax.swing.JTextField();
        eliminarAnime = new javax.swing.JButton();
        returnTo_menu_3 = new javax.swing.JButton();
        dialogoModificar_anime = new javax.swing.JDialog();
        tituloModificar_anime1 = new javax.swing.JLabel();
        idAnimeText2 = new javax.swing.JLabel();
        textfieldModificar_Anime1 = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        returnTo_menu_4 = new javax.swing.JButton();
        nuevoIDText3 = new javax.swing.JLabel();
        textfieldNuevo_id1 = new javax.swing.JTextField();
        botonAgregar_anime = new javax.swing.JButton();
        botonAgregar_ano = new javax.swing.JButton();
        botonMostrar_ano = new javax.swing.JButton();
        botonBuscar_porAno = new javax.swing.JButton();
        closeBoton = new javax.swing.JButton();
        botonEliminar_anime1 = new javax.swing.JButton();
        botonModificar_anime1 = new javax.swing.JButton();

        dialogoAdd_anime.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoAdd_anime.setTitle("Ingrese Datos Del Anime A Agregar");
        dialogoAdd_anime.setAlwaysOnTop(true);
        dialogoAdd_anime.setPreferredSize(new java.awt.Dimension(550, 550));
        dialogoAdd_anime.setResizable(false);
        dialogoAdd_anime.setSize(new java.awt.Dimension(550, 550));

        id_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_inputActionPerformed(evt);
            }
        });

        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        returnTo_menu.setText("Volver al Menu");
        returnTo_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTo_menuActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Ingrese Datos Del Anime A Agregar");

        iD_display.setText("iD");

        nameDisplay.setText("Nombre");

        typeDisplay.setText("Tipo");

        chaptersDisplay.setText("Capitulos");

        durationDisplay.setText("Duracion");

        ratingDisplay.setText("Publico Objetivo");

        yearDisplay.setText("Año");

        studioDisplay.setText("Estudio");

        genreDisplay.setText("Genero");

        javax.swing.GroupLayout dialogoAdd_animeLayout = new javax.swing.GroupLayout(dialogoAdd_anime.getContentPane());
        dialogoAdd_anime.getContentPane().setLayout(dialogoAdd_animeLayout);
        dialogoAdd_animeLayout.setHorizontalGroup(
            dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAdd_animeLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title)
                    .addGroup(dialogoAdd_animeLayout.createSequentialGroup()
                        .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iD_display, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studioDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chaptersDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dialogoAdd_animeLayout.createSequentialGroup()
                                .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(returnTo_menu))
                            .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(episodes_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duration_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rating_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studio_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genre_input, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(115, 115, 115))
        );
        dialogoAdd_animeLayout.setVerticalGroup(
            dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAdd_animeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(title)
                .addGap(41, 41, 41)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iD_display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDisplay)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeDisplay)
                    .addComponent(type_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(episodes_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chaptersDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duration_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studio_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studioDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(dialogoAdd_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnTo_menu)
                    .addComponent(Ingresar))
                .addGap(61, 61, 61))
        );

        dialogoAgregar_ano.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoAgregar_ano.setAlwaysOnTop(true);
        dialogoAgregar_ano.setResizable(false);
        dialogoAgregar_ano.setSize(new java.awt.Dimension(550, 550));

        tituloAdd_ano.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloAdd_ano.setText("Ingrese Año A Agregar");

        anoText.setText("Año");

        toAdd_ano.setOpaque(false);

        addAno.setText("Ingresar");
        addAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnoActionPerformed(evt);
            }
        });

        returnTo_menu_2.setText("Volver al Menu");
        returnTo_menu_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTo_menu_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAgregar_anoLayout = new javax.swing.GroupLayout(dialogoAgregar_ano.getContentPane());
        dialogoAgregar_ano.getContentPane().setLayout(dialogoAgregar_anoLayout);
        dialogoAgregar_anoLayout.setHorizontalGroup(
            dialogoAgregar_anoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAgregar_anoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(anoText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dialogoAgregar_anoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAgregar_anoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(tituloAdd_ano))
                    .addGroup(dialogoAgregar_anoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(dialogoAgregar_anoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toAdd_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoAgregar_anoLayout.createSequentialGroup()
                                .addComponent(addAno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(returnTo_menu_2)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        dialogoAgregar_anoLayout.setVerticalGroup(
            dialogoAgregar_anoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAgregar_anoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloAdd_ano)
                .addGap(46, 46, 46)
                .addGroup(dialogoAgregar_anoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoText)
                    .addComponent(toAdd_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(dialogoAgregar_anoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAno)
                    .addComponent(returnTo_menu_2))
                .addGap(64, 64, 64))
        );

        dialogoMostrar_anos.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoMostrar_anos.setAlwaysOnTop(true);
        dialogoMostrar_anos.setPreferredSize(new java.awt.Dimension(200, 300));
        dialogoMostrar_anos.setResizable(false);
        dialogoMostrar_anos.setSize(new java.awt.Dimension(200, 300));

        title2.setEditable(false);
        title2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title2.setText("Lista De Años");
        title2.setBorder(null);
        title2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title2ActionPerformed(evt);
            }
        });

        returnTo_menu_1.setText("Volver al Menu");
        returnTo_menu_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTo_menu_1ActionPerformed(evt);
            }
        });

        tablaDe_anos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null}
            },
            new String []
            {
                "Año"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDe_anos);
        if (tablaDe_anos.getColumnModel().getColumnCount() > 0) {
            tablaDe_anos.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout dialogoMostrar_anosLayout = new javax.swing.GroupLayout(dialogoMostrar_anos.getContentPane());
        dialogoMostrar_anos.getContentPane().setLayout(dialogoMostrar_anosLayout);
        dialogoMostrar_anosLayout.setHorizontalGroup(
            dialogoMostrar_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoMostrar_anosLayout.createSequentialGroup()
                .addGroup(dialogoMostrar_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoMostrar_anosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoMostrar_anosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(returnTo_menu_1)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoMostrar_anosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        dialogoMostrar_anosLayout.setVerticalGroup(
            dialogoMostrar_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoMostrar_anosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(returnTo_menu_1)
                .addGap(25, 25, 25))
        );

        dialogoBuscar_porAnos.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoBuscar_porAnos.setAlwaysOnTop(true);
        dialogoBuscar_porAnos.setPreferredSize(new java.awt.Dimension(430, 300));
        dialogoBuscar_porAnos.setResizable(false);
        dialogoBuscar_porAnos.setSize(new java.awt.Dimension(430, 300));

        ano4.setEditable(false);
        ano4.setText("Año");
        ano4.setOpaque(false);
        ano4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ano4ActionPerformed(evt);
            }
        });

        inputAno.setOpaque(false);

        botonBusca_ano.setText("Buscar");
        botonBusca_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusca_anoActionPerformed(evt);
            }
        });

        tituloJDialog4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloJDialog4.setText("Ingrese el año a buscar");

        javax.swing.GroupLayout dialogoBuscar_porAnosLayout = new javax.swing.GroupLayout(dialogoBuscar_porAnos.getContentPane());
        dialogoBuscar_porAnos.getContentPane().setLayout(dialogoBuscar_porAnosLayout);
        dialogoBuscar_porAnosLayout.setHorizontalGroup(
            dialogoBuscar_porAnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoBuscar_porAnosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(ano4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(dialogoBuscar_porAnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBusca_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoBuscar_porAnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloJDialog4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        dialogoBuscar_porAnosLayout.setVerticalGroup(
            dialogoBuscar_porAnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoBuscar_porAnosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloJDialog4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(dialogoBuscar_porAnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ano4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(botonBusca_ano)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        outputFiltro_porAno.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        outputFiltro_porAno.setAlwaysOnTop(true);
        outputFiltro_porAno.setResizable(false);
        outputFiltro_porAno.setSize(new java.awt.Dimension(1115, 551));

        tablaFiltrados_porAno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Capitulos", "Duracion", "Clasificacion de contenidos", "Año", "Estudio", "Genero(s)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFiltrados_porAno.setCellSelectionEnabled(true);
        tablaFiltrados_porAno.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaFiltrados_porAno);
        tablaFiltrados_porAno.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tablaFiltrados_porAno.getColumnModel().getColumnCount() > 0) {
            tablaFiltrados_porAno.getColumnModel().getColumn(0).setPreferredWidth(64);
            tablaFiltrados_porAno.getColumnModel().getColumn(2).setPreferredWidth(16);
            tablaFiltrados_porAno.getColumnModel().getColumn(3).setPreferredWidth(40);
            tablaFiltrados_porAno.getColumnModel().getColumn(6).setPreferredWidth(64);
        }

        jButton1.setText("Volver al Menu");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outputFiltro_porAnoLayout = new javax.swing.GroupLayout(outputFiltro_porAno.getContentPane());
        outputFiltro_porAno.getContentPane().setLayout(outputFiltro_porAnoLayout);
        outputFiltro_porAnoLayout.setHorizontalGroup(
            outputFiltro_porAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
            .addGroup(outputFiltro_porAnoLayout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(jButton1))
        );
        outputFiltro_porAnoLayout.setVerticalGroup(
            outputFiltro_porAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputFiltro_porAnoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setPreferredSize(new java.awt.Dimension(400, 210));
        errorDialog.setSize(new java.awt.Dimension(400, 210));

        volverA_menuFrom_error.setText("Volver al Menu");
        volverA_menuFrom_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverA_menuFrom_errorActionPerformed(evt);
            }
        });

        tituloError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloError.setText("ERROR!");

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(volverA_menuFrom_error, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(tituloError)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tituloError)
                .addGap(76, 76, 76)
                .addComponent(volverA_menuFrom_error)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        okDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        okDialog.setAlwaysOnTop(true);

        javax.swing.GroupLayout okDialogLayout = new javax.swing.GroupLayout(okDialog.getContentPane());
        okDialog.getContentPane().setLayout(okDialogLayout);
        okDialogLayout.setHorizontalGroup(
            okDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        okDialogLayout.setVerticalGroup(
            okDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dialogoEliminar_anime.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoEliminar_anime.setAlwaysOnTop(true);
        dialogoEliminar_anime.setResizable(false);
        dialogoEliminar_anime.setSize(new java.awt.Dimension(550, 550));

        tituloEliminar_anime1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloEliminar_anime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloEliminar_anime1.setText("Ingrese ID del Anime A Eliminar");

        idAnimeText1.setText("ID Anime");

        textfieldEliminar_Anime1.setOpaque(false);

        eliminarAnime.setText("Eliminar");
        eliminarAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAnimeActionPerformed(evt);
            }
        });

        returnTo_menu_3.setText("Volver al Menu");
        returnTo_menu_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTo_menu_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoEliminar_animeLayout = new javax.swing.GroupLayout(dialogoEliminar_anime.getContentPane());
        dialogoEliminar_anime.getContentPane().setLayout(dialogoEliminar_animeLayout);
        dialogoEliminar_animeLayout.setHorizontalGroup(
            dialogoEliminar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoEliminar_animeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(idAnimeText1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoEliminar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfieldEliminar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogoEliminar_animeLayout.createSequentialGroup()
                        .addComponent(eliminarAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnTo_menu_3)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(tituloEliminar_anime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogoEliminar_animeLayout.setVerticalGroup(
            dialogoEliminar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoEliminar_animeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloEliminar_anime1)
                .addGap(46, 46, 46)
                .addGroup(dialogoEliminar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAnimeText1)
                    .addComponent(textfieldEliminar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(dialogoEliminar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarAnime)
                    .addComponent(returnTo_menu_3))
                .addGap(64, 64, 64))
        );

        dialogoModificar_anime.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoModificar_anime.setAlwaysOnTop(true);
        dialogoModificar_anime.setResizable(false);
        dialogoModificar_anime.setSize(new java.awt.Dimension(550, 550));

        tituloModificar_anime1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloModificar_anime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloModificar_anime1.setText("Ingrese ID del Anime A Modificar");

        idAnimeText2.setText("ID Anime");

        textfieldModificar_Anime1.setOpaque(false);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        returnTo_menu_4.setText("Volver al Menu");
        returnTo_menu_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTo_menu_4ActionPerformed(evt);
            }
        });

        nuevoIDText3.setText("Nuevo ID");

        textfieldNuevo_id1.setOpaque(false);

        javax.swing.GroupLayout dialogoModificar_animeLayout = new javax.swing.GroupLayout(dialogoModificar_anime.getContentPane());
        dialogoModificar_anime.getContentPane().setLayout(dialogoModificar_animeLayout);
        dialogoModificar_animeLayout.setHorizontalGroup(
            dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloModificar_anime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialogoModificar_animeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificar_animeLayout.createSequentialGroup()
                        .addComponent(nuevoIDText3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textfieldNuevo_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificar_animeLayout.createSequentialGroup()
                        .addComponent(idAnimeText2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfieldModificar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoModificar_animeLayout.createSequentialGroup()
                                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(returnTo_menu_4)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        dialogoModificar_animeLayout.setVerticalGroup(
            dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoModificar_animeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloModificar_anime1)
                .addGap(46, 46, 46)
                .addGroup(dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAnimeText2)
                    .addComponent(textfieldModificar_Anime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoIDText3)
                    .addComponent(textfieldNuevo_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(dialogoModificar_animeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(returnTo_menu_4))
                .addGap(64, 64, 64))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moai AnimeList");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(430, 500));

        botonAgregar_anime.setText("Agregar Anime");
        botonAgregar_anime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar_animeActionPerformed(evt);
            }
        });

        botonAgregar_ano.setText("Agregar Año de Publicacion");
        botonAgregar_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar_anoActionPerformed(evt);
            }
        });

        botonMostrar_ano.setText("Mostrar Años");
        botonMostrar_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrar_anoActionPerformed(evt);
            }
        });

        botonBuscar_porAno.setText("Mostrar Animes de \"x\" año");
        botonBuscar_porAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar_porAnoActionPerformed(evt);
            }
        });

        closeBoton.setText("Cerrar Aplicacion :c");
        closeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBotonActionPerformed(evt);
            }
        });

        botonEliminar_anime1.setText("Eliminar anime");
        botonEliminar_anime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar_anime1ActionPerformed(evt);
            }
        });

        botonModificar_anime1.setText("Modificar anime");
        botonModificar_anime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificar_anime1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonModificar_anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonEliminar_anime1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(closeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregar_anime, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscar_porAno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMostrar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregar_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botonAgregar_anime)
                .addGap(18, 18, 18)
                .addComponent(botonAgregar_ano)
                .addGap(18, 18, 18)
                .addComponent(botonMostrar_ano)
                .addGap(18, 18, 18)
                .addComponent(botonBuscar_porAno)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar_anime1)
                .addGap(18, 18, 18)
                .addComponent(botonModificar_anime1)
                .addGap(71, 71, 71)
                .addComponent(closeBoton)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregar_animeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAgregar_animeActionPerformed
    {//GEN-HEADEREND:event_botonAgregar_animeActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            dialogoAdd_anime.setVisible(true);
    }//GEN-LAST:event_botonAgregar_animeActionPerformed

    private void closeBotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeBotonActionPerformed
    {//GEN-HEADEREND:event_closeBotonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeBotonActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_name_inputActionPerformed
    {//GEN-HEADEREND:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void clearFields()
    {
        id_input.setText("");
        name_input.setText("");
        type_input.setText("");
        episodes_input.setText("");
        duration_input.setText("");
        rating_input.setText("");
        year_input.setText("");
        studio_input.setText("");
        genre_input.setText("");
        inputAno.setText("");
        toAdd_ano.setText("");
        textfieldEliminar_Anime1.setText("");
        textfieldModificar_Anime1.setText("");
        textfieldNuevo_id1.setText("");
    }
    
    private void IngresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_IngresarActionPerformed
    {//GEN-HEADEREND:event_IngresarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(id_input.getText());
        String name = name_input.getText();
        String type = type_input.getText();
        int episodes = Integer.parseInt(episodes_input.getText());
        String duration = duration_input.getText();
        String rating = rating_input.getText();
        int year = Integer.parseInt(year_input.getText());
        String studio = studio_input.getText();
        String genre = genre_input.getText();
        Anime newanime = new Anime(id,name,type,episodes,duration,rating,year,studio,genre);
        llamar.addAnime(newanime);
        this.dialogoAdd_anime.dispose();
        clearFields();
        this.setVisible(true);
    }//GEN-LAST:event_IngresarActionPerformed

    private void id_inputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_id_inputActionPerformed
    {//GEN-HEADEREND:event_id_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_inputActionPerformed

    private void botonAgregar_anoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAgregar_anoActionPerformed
    {//GEN-HEADEREND:event_botonAgregar_anoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dialogoAgregar_ano.setVisible(true);
    }//GEN-LAST:event_botonAgregar_anoActionPerformed

    private void returnTo_menuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnTo_menuActionPerformed
    {//GEN-HEADEREND:event_returnTo_menuActionPerformed
        // TODO add your handling code here:
        this.dialogoAdd_anime.dispose();
        clearFields();
        this.setVisible(true);
    }//GEN-LAST:event_returnTo_menuActionPerformed

    private void returnTo_menu_1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnTo_menu_1ActionPerformed
    {//GEN-HEADEREND:event_returnTo_menu_1ActionPerformed
        // TODO add your handling code here:
        dialogoMostrar_anos.dispose();
        clearFields();
        this.setVisible(true);
    }//GEN-LAST:event_returnTo_menu_1ActionPerformed

    private void botonBusca_anoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBusca_anoActionPerformed
    {//GEN-HEADEREND:event_botonBusca_anoActionPerformed
        // TODO add your handling code here:
        String ano1=inputAno.getText();
        int exist =rellenarTabla_anos(ano1);
        clearFields();
        dialogoBuscar_porAnos.dispose();
        if(exist!=0)
        {
            errorDialog.setVisible(true);
            return;
        }
        outputFiltro_porAno.setVisible(true);
    }//GEN-LAST:event_botonBusca_anoActionPerformed

    private void botonBuscar_porAnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscar_porAnoActionPerformed
    {//GEN-HEADEREND:event_botonBuscar_porAnoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dialogoBuscar_porAnos.setVisible(true);
    }//GEN-LAST:event_botonBuscar_porAnoActionPerformed

    private void ano4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ano4ActionPerformed
    {//GEN-HEADEREND:event_ano4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ano4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        outputFiltro_porAno.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volverA_menuFrom_errorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volverA_menuFrom_errorActionPerformed
    {//GEN-HEADEREND:event_volverA_menuFrom_errorActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_volverA_menuFrom_errorActionPerformed

    private void title2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_title2ActionPerformed
    {//GEN-HEADEREND:event_title2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title2ActionPerformed

    private void botonMostrar_anoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonMostrar_anoActionPerformed
    {//GEN-HEADEREND:event_botonMostrar_anoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        tablaDe_anos.setModel(new javax.swing.table.DefaultTableModel
        (
            llamar.getYears(),
            new String []
            {
                "Año"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        dialogoMostrar_anos.setVisible(true);
    }//GEN-LAST:event_botonMostrar_anoActionPerformed

    private void addAnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addAnoActionPerformed
    {//GEN-HEADEREND:event_addAnoActionPerformed
        // TODO add your handling code here:
        int flag;
        String inputAno;
        inputAno =toAdd_ano.getText();
        flag =llamar.addYear(inputAno);
        dialogoAgregar_ano.dispose();
        clearFields();
        if (flag!=0)
        {    
            errorDialog.setVisible(true);
            return;
        }
        this.setVisible(true);
    }//GEN-LAST:event_addAnoActionPerformed

    private void returnTo_menu_2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnTo_menu_2ActionPerformed
    {//GEN-HEADEREND:event_returnTo_menu_2ActionPerformed
        // TODO add your handling code here:
        dialogoAgregar_ano.dispose();
        clearFields();
        this.setVisible(true);
    }//GEN-LAST:event_returnTo_menu_2ActionPerformed

    private void botonEliminar_anime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar_anime1ActionPerformed
        this.setVisible(false);
        this.dialogoEliminar_anime.setVisible(true);
    }//GEN-LAST:event_botonEliminar_anime1ActionPerformed

    private void eliminarAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAnimeActionPerformed
        String animeID = this.textfieldEliminar_Anime1.getText();
        int eliminarID = llamar.eliminarAnime(animeID);
        this.dialogoEliminar_anime.dispose();
        if(eliminarID != 0){
            errorDialog.setVisible(true);
            return;
        }
        this.setVisible(true);
        clearFields();
    }//GEN-LAST:event_eliminarAnimeActionPerformed

    private void returnTo_menu_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnTo_menu_3ActionPerformed
        dialogoEliminar_anime.dispose();
        clearFields();
        this.setVisible(true);
    }//GEN-LAST:event_returnTo_menu_3ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String animeID = textfieldModificar_Anime1.getText();
        String nuevoID = textfieldNuevo_id1.getText();
        int modificarID = llamar.modificarID(animeID, nuevoID);
        this.dialogoModificar_anime.dispose();
        if(modificarID != 0){
            errorDialog.setVisible(true);
            return;
        }
        this.setVisible(true);
        clearFields();
    }//GEN-LAST:event_ModificarActionPerformed

    private void returnTo_menu_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnTo_menu_4ActionPerformed
        dialogoModificar_anime.dispose();
        clearFields();
        this.setVisible(true);
    }//GEN-LAST:event_returnTo_menu_4ActionPerformed

    private void botonModificar_anime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificar_anime1ActionPerformed
        this.setVisible(false);
        dialogoModificar_anime.setVisible(true);
    }//GEN-LAST:event_botonModificar_anime1ActionPerformed

    private int rellenarTabla_anos(String ano)
    {
        Object tablaAnos[][] =null;
        tablaAnos =llamar.mostrarDel_ano(tablaAnos,ano);
        if (tablaAnos==null)
        {
            return(-1);
        }
        else
        {
            tablaFiltrados_porAno.setModel(new javax.swing.table.DefaultTableModel
            (
                tablaAnos,
                new String []
                {
                    "ID", "Nombre", "Tipo", "Capitulos", "Duracion", "Clasificacion de contenidos", "Año", "Estudio", "Genero(s)"
                }
            )
            {
                Class[] types = new Class []
                {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean []
                {
                    false, false, false, false, false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex)
                {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex)
                {
                    return canEdit [columnIndex];
                }
            });
        }
        return(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws FileNotFoundException,IOException
    {
        llamar.importCatalogue();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton addAno;
    private javax.swing.JTextField ano4;
    private javax.swing.JLabel anoText;
    private javax.swing.JButton botonAgregar_anime;
    private javax.swing.JButton botonAgregar_ano;
    private javax.swing.JButton botonBusca_ano;
    private javax.swing.JButton botonBuscar_porAno;
    private javax.swing.JButton botonEliminar_anime1;
    private javax.swing.JButton botonModificar_anime1;
    private javax.swing.JButton botonMostrar_ano;
    private javax.swing.JLabel chaptersDisplay;
    private javax.swing.JButton closeBoton;
    private javax.swing.JDialog dialogoAdd_anime;
    private javax.swing.JDialog dialogoAgregar_ano;
    private javax.swing.JDialog dialogoBuscar_porAnos;
    private javax.swing.JDialog dialogoEliminar_anime;
    private javax.swing.JDialog dialogoModificar_anime;
    private javax.swing.JDialog dialogoMostrar_anos;
    private javax.swing.JLabel durationDisplay;
    private javax.swing.JTextField duration_input;
    private javax.swing.JButton eliminarAnime;
    private javax.swing.JTextField episodes_input;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel genreDisplay;
    private javax.swing.JTextField genre_input;
    private javax.swing.JLabel iD_display;
    private javax.swing.JLabel idAnimeText1;
    private javax.swing.JLabel idAnimeText2;
    private javax.swing.JTextField id_input;
    private javax.swing.JTextField inputAno;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel nuevoIDText3;
    private javax.swing.JDialog okDialog;
    private javax.swing.JDialog outputFiltro_porAno;
    private javax.swing.JLabel ratingDisplay;
    private javax.swing.JTextField rating_input;
    private javax.swing.JButton returnTo_menu;
    private javax.swing.JButton returnTo_menu_1;
    private javax.swing.JButton returnTo_menu_2;
    private javax.swing.JButton returnTo_menu_3;
    private javax.swing.JButton returnTo_menu_4;
    private javax.swing.JLabel studioDisplay;
    private javax.swing.JTextField studio_input;
    private javax.swing.JTable tablaDe_anos;
    private javax.swing.JTable tablaFiltrados_porAno;
    private javax.swing.JTextField textfieldEliminar_Anime1;
    private javax.swing.JTextField textfieldModificar_Anime1;
    private javax.swing.JTextField textfieldNuevo_id1;
    private javax.swing.JLabel title;
    private javax.swing.JTextField title2;
    private javax.swing.JLabel tituloAdd_ano;
    private javax.swing.JLabel tituloEliminar_anime1;
    private javax.swing.JLabel tituloError;
    private javax.swing.JTextField tituloJDialog4;
    private javax.swing.JLabel tituloModificar_anime1;
    private javax.swing.JTextField toAdd_ano;
    private javax.swing.JLabel typeDisplay;
    private javax.swing.JTextField type_input;
    private javax.swing.JButton volverA_menuFrom_error;
    private javax.swing.JLabel yearDisplay;
    private javax.swing.JTextField year_input;
    // End of variables declaration//GEN-END:variables
}
